# Generated by Django 4.1.5 on 2023-01-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_category_alter_perk_details_and_more'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vidio',
            new_name='Video',
        ),
    ]
