# Generated by Django 4.1.5 on 2023-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0004_alter_photo_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
