# Generated by Django 4.1.5 on 2023-02-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_amenities_alter_room_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descriptrion',
            new_name='description',
        ),
    ]
